database:
  hikari:
    minimumIdle: 3
    maximum-pool-size: 15
    auto-commit: false
    username: "postgres"
    password: "pass"
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5434/postgres



